### ISSUE TITLE
MAC OSX: Buffer Underflow exception when reading DDS files

### ISSUE THREAD

**Issue by cschar** [vs49688/RAFTools#9]
Hi, Tried taking your project for a spin.

I'm on a macbook, running jdk 1.8, 
did the following
```
1.  gradle build
2. java -jar ./build/libs/RAFTools.jar
3. (Select the League of Legends.app file located in the root /Applications folder)
4. after loading
5. Tried looking at character DDS files for their skins 
After clicking on files, errors similar to the one below appeared:
```

Exception in thread "AWT-EventQueue-0" java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at net.vs49688.rafview.dds.DDSImage$Header.read(DDSImage.java:610)
	at net.vs49688.rafview.dds.DDSImage.readFromBuffer(DDSImage.java:714)
	at net.vs49688.rafview.dds.DDSImage.read(DDSImage.java:195)
	at net.vs49688.rafview.gui.DDSViewer.setDDS(DDSViewer.java:68)
	at net.vs49688.rafview.gui.Controller$DDSDelayedLoader.lambda$load$0(Controller.java:394)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any clues? Thanks.

**Comment by vs49688** [comment]
Hi, which DDS file was it? It's possible it's in a format that's not supported. If so, I can probably add support relatively easily

**Comment by cschar** [comment]
yeah <3 ! works!
